-- SELECT column, another_table_column, …
-- FROM mytable
-- INNER JOIN another_table
-- ON mytable.id = another_table.id
-- WHERE condition(s)
-- ORDER BY column, … ASC/DESC
-- LIMIT num_limit OFFSET num_offset;

-- SELECT DISTINCT building_name, role
-- FROM buildings
-- LEFT JOIN employees
-- ON building_name = building;